### ISSUE TITLE
查询 1 月份（2022.1 和 2021.1）的字幕时出现错误

### ISSUE THREAD

**Issue by HandwerSTD** [A-Soul-Database/API#1]
https://github.com/A-Soul-Database/API/commit/4b33f3e5727c759c1019435385560d0cd63d77b2
这个 commit 里面引入了一个对 month 的特判，但是下面（115 行）还有一个对 `int(month) = 1` 的特判，会造成访问 1 月份的时候 URL 变成 `/2022/001/` 而不是 `/2022/01/`

**Comment by P-PPPP** [comment]
Fixed :)
